### ISSUE TITLE
Home Screen Shortcuts created in Chrome do not appear on Home Screen

### ISSUE THREAD

**Issue by fishears** [LawnchairLauncher/Lawnchair#111]
In Chrome there is an "Add to Home screen" option to add a shortcut to any web page on your home screen - like it was an app. When I do this Chrome says that the shortcut was added but it does not appear anywhere  in Lawnchair.

**Comment by ndzaky97** [comment]
I can confirm it is working on mine. But the icons is so huge.

**Comment by fishears** [comment]
Sorry, I should have given more detail: Lawnchair version 198, stock Android 8.0 DP3, Nexus 5x, latest Chrome stable

**Comment by paphonbth** [comment]
Newer Chrome versions add PWAs to the app drawer and not the home screen. Did you check that?

**Comment by fishears** [comment]
This is still an issue for me. Now running build 297. Everything is added to homescreen with Google Now launcher but I get nothing with Lawnchair. It does work on my tablet but that's running LineageOS 14.1 (Android 7.1.2). I've now run another test from the Google Weather app which has a "add to desktop" option and this adds the shortcut to weather on my tab but not on my phone.

**Comment by acofalc** [comment]
I have the same problem. Says that icon is added but nothing shows on Lawnchair. Tried from Chrome and Google Weather app. Version 818, Nexus 6P, Android O DP3.

**Comment by intelligentcasanova** [comment]
Have you tried it on the latest build?

**Comment by fishears** [comment]
Just tried on latest build. Still not working. It works on my tablet running 7.1.2 just not on my phone running 8.0

**Comment by chromaniac2** [comment]
I had this issue with custom launchers on Android O DP builds. I upgraded to Android Orea stable build last night and the same issue persists. Resetting the phone did not help. Chrome shortcuts only appear on Google launcher for me (Nexus 6P). I have tried creating shortcuts on Evie, Nova and Lawnchair with zero success. This is forcing me to use Google launcher for the time being which is painful. I would really like to know if this is a bug or something at my end. Because a friend with Pixel does not have this problem on his phone. 

PS. I am creating regular web shortcuts which are not Progressive Web Apps. These do not appear inside launcher.

**Comment by h3ndrk** [comment]
Same on my Nexus 5X, running Android 8.0.0 (beta, 5th august patches). For me the Telegram messenger is unable to install shortcuts to the home screen. The Chrome-like browser 'Brave' has the same problem. When triggering such an option to install anything to the home screen, nothing happens. I'm remembering some kind of a badge/notice in the stock Google Launcher saying something like "Added shortcut to home screen" (maybe this was back in Android 7?). This badge/notice is missing, it just happens anything.

When running `adb logcat` on my device I found something interesting:

```
09-07 16:33:45.316  3403  5895 W ActivityManager: Broadcast com.android.launcher.action.INSTALL_SHORTCUT no longer supported. It will not be delivered.
```

Taken from a comment on another issue: 

> The com.android.launcher.action.INSTALL_SHORTCUT broadcast no longer has any effect on your app, because it is now a private, implicit broadcast. Instead, you should create an app shortcut by using the requestPinShortcut() method from the ShortcutManager class.

Source of the quote: https://github.com/expo/expo/issues/491#issuecomment-322063731

https://developer.android.com/preview/behavior-changes.html (this page does not load for me :cry:)

Looks for me like an API change at the app developer side. This would mean that the launcher cannot do anything to fix this issue, the apps must use a different API.

I'm not an expert, everything above is kind of guessing. Maybe someone can confirm this? Thanks!

**Comment by h3ndrk** [comment]
This might also help: https://stackoverflow.com/q/44744184

**Comment by chromaniac2** [comment]
Nova has finally fixed this in their recent builds.

**Comment by JacobDB** [comment]
I'm seeing this as well.

**Comment by JacobDB** [comment]
I'm seeing this occur as well; running the latest stable release on Android 8.0 on a Pixel XL. This seems to happen for anything trying to add a shortcut to home, including installing apps from Google Play.

**Comment by m-p-3** [comment]
Unable to add a shortcut to a website to the Lawnchair's Launcher 1.0.1063 using Google Chrome 61.0.3163.98 on Nexus6P Android 8.0.0 (OPR6.170623.019).

No shortcut will show up on the launcher, even after multiple attempts.

**Comment by mjeshurun** [comment]
Same issue here with Nexus 5X running latest Android 8.
As a temporary solution, I used Tasker to create a home screen shortcut to open a URL. 
Look for Browse URL task.

**Comment by rodimvs** [comment]
Same issue here; Lawnchair 1.0.1063, Nexus 5X, Android 8.

**Comment by dowahwiddy** [comment]
Same issue still ongoing 1.0.1483, nexus 6p, Oreo 8.1

**Comment by doon386** [comment]
Same here. Pixel2, Oreo 8.0

**Comment by LoggeL** [comment]
Same here tried on Chrome and Firefox. 
OnePlus 3T on Android 8.0
Lawnchair Version 1.1.0.1594

**Comment by m-p-3** [comment]
Upgraded my Nexus 6P to Android 8.1, issue is still present.
Also happening on my Xiaomi Mi A1 on 8.0.

**Comment by Zizou3000** [comment]
Same here on android 8, it works on 7.

**Comment by tanapthetimid** [comment]
Same here on Xperia xz1 compact android 8.0 running latest google play store lawnchair build and latest chrome stable build

**Comment by uudruid74** [comment]
Ugh. .. I have a universal remote as a web app and I need quick access to it from the desktop (without the URL bar). This issue persists on latest alpha and its a deal breaker for me.

**Comment by divadsn** [comment]
Please be patient, API changes on Oreo are already taking up time, we are trying to get that for v1 done.

**Comment by Brottweiler** [comment]
@uudruid74 
>its a deal breaker for me

If it's a deal breaker to you maybe you shouldn't use **beta** software.

**Comment by uudruid74** [comment]
@Brottweiler 
> If it's a deal breaker to you maybe you shouldn't use beta software.

Obviously, the point of beta software is to provide feedback to the author (here) so that a variety of use cases can be tested that the author may not have or use.   The developer(s) may not use Oreo or may not use desktop web shortcuts (I need them to control my entertainment center).   I reported the issue without any particular complaint.  In this case, I already said its a deal breaker.  In case your English is bad, this means I am NOT using it any longer.  This isn't a rant or saying it's crap or any other evaluation of quality (for which "beta" would be a excuse).  It means that I can't use it any longer and won't be able to continue further beta testing.  

My apologies for feeding the trolls.

**Comment by divadsn** [comment]
@uudruid74 don't worry, we are already working on that :)

**Comment by psamim** [comment]
Hi,
I have the same problem on my Nexus 5x, Lawnchair 1.1.0.1742, Android 8.0.0.
As PWAs are becoming more and more popular, it seems that it is a relatively important issue.
Thanks

**Comment by bohrabhijeet** [comment]
@psamim The team is working on it. It must be fixed in the final release. Please be patient.

**Comment by psamim** [comment]
@abhijeetbohra Thanks for the quick answer! It just made me worried to see the issue has been open for such a long time.

**Comment by bohrabhijeet** [comment]
@psamim No worries :) 
Just wait a "little bit" more for the final release. It will be there very soon!

**Comment by GAZ082** [comment]
@abhijeetbohra hey there! any clue when the final release is going to be ready? I also need this fixed asap, love the launcher, love Android 8 but this bug either in the Android code or launcher is also a pain in the ass for me.

Thanks!

**Comment by bohrabhijeet** [comment]
@GAZ082 Yo! The closed beta testing is under process. I'd suggest you to wait for the another release. BTW, we have already pushed 2 updates on Play Store, have you checked? 
Talking about this issue, yes, the devs are working on it. ;)

**Comment by adamf663** [comment]
a year later, still not working.

**Comment by nyancrimew** [comment]
@adamf663 This has been fixed now and will be available in the next update

**Comment by adamf663** [comment]
thx

**Comment by GAZ082** [comment]
Please give us a timeline. The next update has been in beta for almost a month and a half. Thanks!

**Comment by divadsn** [comment]
@GAZ082 Lol, now what? Patience, this will be the final release and then v2 will get to the beta phase.

**Comment by GAZ082** [comment]
Why cant you release the beta using Google Play's beta system?

I'm grateful for your effort and I'm not complaining but this buy is REALLY a pain the ass and the closed beta has been for quite a long time. This is a launcher after all, not something really complex that requires a ton of testing.

**Comment by nyancrimew** [comment]
@GAZ082 We are releasing using the google play beta system but as the entire app is currently ONLY in beta the only active channel is the beta channel

**Comment by divadsn** [comment]
@GAZ082 Actually the app is already beta on the Play Store, it's just Google derping and showing unreleased instead of beta in the app title, but no worries, only final polishing is now on our list, but most of us have barely time due to the final grades which are at the end of May in most high schools.

**Comment by dreemesicle** [comment]
I sure hope this matter is resolved soon. I too, rely on adding shortcuts to web pages on my home screens. Has not worked since getting my new phone 2 mths ago (Samsung Galaxy S8) I've spent so much time researching this and trying to find the  problem with no luck. Not sure if this matters but I'm currently using Go Launcher
Thanks so much!
Diann

**Comment by adamf663** [comment]
I apparently posted in the wrong forum when I searched for others who couldn't save a desktop link from chrome.
I'm actually a go launcher user, but I grabbed lawnchair and it looks very promising.  
Sounds like LC has it fixed and it's time to switch. :-)  Can LC do multiple pages?  

----- Original Message -----

**Comment by bohrabhijeet** [comment]
@adamf663 Wdym by multiple pages? It can add multiple pages, yes.

**Comment by WalkerWalker** [comment]
Same issue occured to me . Glad I'm not the only one

**Comment by divadsn** [comment]
The fix has been already merged, please be patient and wait for the update or build an APK yourself, closing.

**Comment by Fmilich** [comment]
What in the hell did you do away with the add to home screen button in the first damn place? No answer could be satisfactory to me, So I'll be looking for a new browser! STUPID IS STUPID IS STUPID!

**Comment by fischermatte** [comment]
any news on this? not working on s7 oreo. tried with Firefox, Chrome and Brave.

**Comment by rocka** [comment]
I found out that if "Settings - Home Screen - Add icon to Home Screen (for new apps)" was disabled, no Apps can add icon to home screen, even if you click "Add to Home Screen" manually in Chrome.

But if that was enabled, some Shortcuts still  cannot be added to Home Screen, for example, search "weather" in Google App, click that three-dot menu on top right of the 1st weather card, then click "add a home screen shortcut". You will be back to the home screen, but nothing would be added.

**Comment by ghost** [comment]
Exact same set up as @fischermatte, still not working.

**Comment by psi-4ward** [comment]
still not working

**Comment by StevieMJH** [comment]
Bug sure is hanging around a long time for also being worked on.

**Comment by bohrabhijeet** [comment]
@StevieMJH I'll let the developers know of this and hope to get the bug fixed in future builds.

**Comment by avinash** [comment]
Still not working in the latest version of Lawnchair. Tested on two different phones running Android 9 and 10.

**Comment by Kaympe20** [comment]
Still not working
